database:
  image: postgres:9.5
  environment:
    POSTGRES_USER: masimomi
    POSTGRES_PASSWORD: momimasi
  ports:
    - '5433:5433'
  volumes:
    - ~/.docker-volumes/masimomi/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:2.8.22
  ports:
    - '6380:6380'
  volumes:
    - ~/.docker-volumes/masimomi/redis/data:/var/lib/redis/data

masimomi:
  build: .
  links:
    - database
    - redis
  volumes:
    - .:/masimomi
  ports:
    - '8001:8001'
  env_file:
    - .masimomi.env
